// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResultType int32

const (
	ResultType_ResultOK           ResultType = 0
	ResultType_ResultErrCheckAuth ResultType = 1
	ResultType_ResultErrRedis     ResultType = 2
	ResultType_ResultErrInner     ResultType = 3
	ResultType_ResultErrSaveMsg   ResultType = 4
	ResultType_ResultErrParam     ResultType = 5
)

var ResultType_name = map[int32]string{
	0: "ResultOK",
	1: "ResultErrCheckAuth",
	2: "ResultErrRedis",
	3: "ResultErrInner",
	4: "ResultErrSaveMsg",
	5: "ResultErrParam",
}

var ResultType_value = map[string]int32{
	"ResultOK":           0,
	"ResultErrCheckAuth": 1,
	"ResultErrRedis":     2,
	"ResultErrInner":     3,
	"ResultErrSaveMsg":   4,
	"ResultErrParam":     5,
}

func (x ResultType) String() string {
	return proto.EnumName(ResultType_name, int32(x))
}

func (ResultType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

type MsgInfo struct {
	SendUid              string   `protobuf:"bytes,1,opt,name=send_uid,json=sendUid,proto3" json:"send_uid,omitempty"`
	RecvUid              string   `protobuf:"bytes,2,opt,name=recv_uid,json=recvUid,proto3" json:"recv_uid,omitempty"`
	MsgId                uint64   `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgType              string   `protobuf:"bytes,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	MsgBody              string   `protobuf:"bytes,5,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	Attachment           string   `protobuf:"bytes,6,opt,name=attachment,proto3" json:"attachment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgInfo) Reset()         { *m = MsgInfo{} }
func (m *MsgInfo) String() string { return proto.CompactTextString(m) }
func (*MsgInfo) ProtoMessage()    {}
func (*MsgInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *MsgInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgInfo.Unmarshal(m, b)
}
func (m *MsgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgInfo.Marshal(b, m, deterministic)
}
func (m *MsgInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInfo.Merge(m, src)
}
func (m *MsgInfo) XXX_Size() int {
	return xxx_messageInfo_MsgInfo.Size(m)
}
func (m *MsgInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInfo proto.InternalMessageInfo

func (m *MsgInfo) GetSendUid() string {
	if m != nil {
		return m.SendUid
	}
	return ""
}

func (m *MsgInfo) GetRecvUid() string {
	if m != nil {
		return m.RecvUid
	}
	return ""
}

func (m *MsgInfo) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MsgInfo) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MsgInfo) GetMsgBody() string {
	if m != nil {
		return m.MsgBody
	}
	return ""
}

func (m *MsgInfo) GetAttachment() string {
	if m != nil {
		return m.Attachment
	}
	return ""
}

func init() {
	proto.RegisterEnum("common.ResultType", ResultType_name, ResultType_value)
	proto.RegisterType((*MsgInfo)(nil), "common.MsgInfo")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6) }

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4a, 0x33, 0x31,
	0x14, 0x40, 0xbf, 0xf4, 0x67, 0xda, 0xef, 0x2a, 0x12, 0xe2, 0xdf, 0xb8, 0x91, 0xe2, 0xaa, 0xb8,
	0x18, 0x17, 0x3e, 0x81, 0x2d, 0x2e, 0x8a, 0x14, 0xcb, 0xa8, 0xeb, 0x92, 0x4e, 0xae, 0xe9, 0x60,
	0x93, 0x0c, 0x49, 0x5a, 0x9c, 0xbd, 0x8f, 0xe3, 0x43, 0x4a, 0x12, 0x2c, 0x76, 0x75, 0x39, 0xe7,
	0xe4, 0x66, 0x71, 0xe1, 0xb4, 0x32, 0x4a, 0x19, 0x7d, 0x97, 0x46, 0xd1, 0x58, 0xe3, 0x0d, 0xcb,
	0x12, 0xdd, 0x7c, 0x13, 0x18, 0xcc, 0x9d, 0x9c, 0xe9, 0x77, 0xc3, 0xae, 0x60, 0xe8, 0x50, 0x8b,
	0xe5, 0xb6, 0x16, 0x39, 0x19, 0x91, 0xf1, 0xff, 0x72, 0x10, 0xf8, 0xad, 0x16, 0x21, 0x59, 0xac,
	0x76, 0x31, 0x75, 0x52, 0x0a, 0x1c, 0xd2, 0x39, 0x64, 0xca, 0xc9, 0x65, 0x2d, 0xf2, 0xee, 0x88,
	0x8c, 0x7b, 0x65, 0x5f, 0x39, 0x39, 0x8b, 0x1b, 0x41, 0xfb, 0xb6, 0xc1, 0xbc, 0x97, 0x36, 0x94,
	0x93, 0xaf, 0x6d, 0x83, 0xbf, 0x69, 0x65, 0x44, 0x9b, 0xf7, 0xf7, 0x69, 0x62, 0x44, 0xcb, 0xae,
	0x01, 0xb8, 0xf7, 0xbc, 0x5a, 0x2b, 0xd4, 0x3e, 0xcf, 0x62, 0xfc, 0x63, 0x6e, 0xbf, 0x08, 0x40,
	0x89, 0x6e, 0xbb, 0xf1, 0xf1, 0xa7, 0x63, 0x18, 0x26, 0x7a, 0x7e, 0xa2, 0xff, 0xd8, 0x05, 0xb0,
	0x44, 0x8f, 0xd6, 0x4e, 0xd7, 0x58, 0x7d, 0x3c, 0x6c, 0xfd, 0x9a, 0x12, 0xc6, 0xe0, 0x64, 0xef,
	0x4b, 0x14, 0xb5, 0xa3, 0x9d, 0x03, 0x37, 0xd3, 0x1a, 0x2d, 0xed, 0xb2, 0x33, 0xa0, 0x7b, 0xf7,
	0xc2, 0x77, 0x38, 0x77, 0x92, 0xf6, 0x0e, 0x5e, 0x2e, 0xb8, 0xe5, 0x8a, 0xf6, 0x27, 0x63, 0xb8,
	0xac, 0x4d, 0x21, 0x6d, 0x53, 0x15, 0xf8, 0xc9, 0x55, 0xb3, 0x41, 0x57, 0xa4, 0x83, 0x4e, 0x8e,
	0xa6, 0x71, 0x2e, 0xc2, 0x95, 0x17, 0x64, 0x95, 0xc5, 0x73, 0xdf, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0x90, 0x59, 0x05, 0x85, 0x01, 0x00, 0x00,
}
